using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace PureSim.Editor
{
    /// <summary>
    /// Generates PureSimTasksMenu.cs with menu items for each open task.
    /// This file is code-generated and should be regenerated whenever tasks change.
    /// </summary>
    public static class PureSimTasksMenuGenerator
    {
        private const string MenuFilePath = "Assets/Editor/PureSimTasksMenu.cs";
        
        [MenuItem("Tools/PureSim/Regenerate Task Menu")]
        public static void RegenerateMenu()
        {
            string tasksPath = Path.Combine(Application.dataPath, "..", ".copilot/next_steps.json");
            
            if (!File.Exists(tasksPath))
            {
                UnityEngine.Debug.LogWarning("Tasks file not found, cannot regenerate menu");
                return;
            }
            
            try
            {
                string json = File.ReadAllText(tasksPath);
                var wrapper = UnityEngine.JsonUtility.FromJson<TaskListWrapper>("{\"tasks\":" + json + "}");
                var tasks = wrapper.tasks ?? new List<TaskData>();
                
                GenerateMenu(tasks);
            }
            catch (System.Exception e)
            {
                UnityEngine.Debug.LogError($"Failed to regenerate menu: {e.Message}");
            }
        }
        
        public static void GenerateMenu(List<TaskData> tasks)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY");
            sb.AppendLine("// This file is generated by PureSimTasksMenuGenerator");
            sb.AppendLine("// Regenerate using Tools/PureSim/Regenerate Task Menu");
            sb.AppendLine();
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine();
            sb.AppendLine("namespace PureSim.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated menu items for quick access to development tasks.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class PureSimTasksMenu");
            sb.AppendLine("    {");
            
            // Add individual task menu items for open tasks only
            var openTasks = tasks.Where(t => t.status != "done").ToList();
            
            foreach (var task in openTasks)
            {
                string menuName = SanitizeMenuName(task.title);
                string methodName = SanitizeMethodName(task.id);
                
                sb.AppendLine($"        [MenuItem(\"Tools/PureSim/Next Steps/{menuName}\")]");
                sb.AppendLine($"        public static void Open_{methodName}()");
                sb.AppendLine("        {");
                sb.AppendLine($"            PureSimNextStepsWindow.ShowWindow(\"{task.id}\");");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            // Write to file
            File.WriteAllText(MenuFilePath, sb.ToString());
            AssetDatabase.Refresh();
            
            UnityEngine.Debug.Log($"Generated task menu with {openTasks.Count} open tasks");
        }
        
        private static string SanitizeMenuName(string name)
        {
            // Keep menu names readable but valid
            return name.Replace("\"", "'");
        }
        
        private static string SanitizeMethodName(string id)
        {
            // Convert task ID to valid C# identifier
            return id.Replace("-", "_");
        }
        
        [System.Serializable]
        private class TaskListWrapper
        {
            public List<TaskData> tasks;
        }
    }
}
