// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by PureSimTasksMenuGenerator
// Regenerate using Tools/PureSim/Regenerate Task Menu

using UnityEditor;

namespace PureSim.Editor
{
    /// <summary>
    /// Auto-generated menu items for quick access to development tasks.
    /// </summary>
    public static class PureSimTasksMenu
    {
        [MenuItem("Tools/PureSim/Next Steps/Complete Quake Console Core Implementation")]
        public static void Open_console_001()
        {
            PureSimNextStepsWindow.ShowWindow("console-001");
        }

        [MenuItem("Tools/PureSim/Next Steps/Implement Console Command Registry")]
        public static void Open_console_002()
        {
            PureSimNextStepsWindow.ShowWindow("console-002");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create ConsoleOverlayUI Prefab")]
        public static void Open_ui_001()
        {
            PureSimNextStepsWindow.ShowWindow("ui-001");
        }

        [MenuItem("Tools/PureSim/Next Steps/Implement Serial Command Infrastructure")]
        public static void Open_serial_001()
        {
            PureSimNextStepsWindow.ShowWindow("serial-001");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Lsblk Command with Error Paths")]
        public static void Open_serial_002()
        {
            PureSimNextStepsWindow.ShowWindow("serial-002");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Mount Command with Error Paths")]
        public static void Open_serial_003()
        {
            PureSimNextStepsWindow.ShowWindow("serial-003");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Minimal SimulationState Class")]
        public static void Open_sim_001()
        {
            PureSimNextStepsWindow.ShowWindow("sim-001");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Minimal WorkflowEngine")]
        public static void Open_sim_002()
        {
            PureSimNextStepsWindow.ShowWindow("sim-002");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Console Parser Tests")]
        public static void Open_test_001()
        {
            PureSimNextStepsWindow.ShowWindow("test-001");
        }

        [MenuItem("Tools/PureSim/Next Steps/Create Golden Transcript Tests")]
        public static void Open_test_002()
        {
            PureSimNextStepsWindow.ShowWindow("test-002");
        }

        [MenuItem("Tools/PureSim/Next Steps/Document Dual Console Architecture")]
        public static void Open_doc_001()
        {
            PureSimNextStepsWindow.ShowWindow("doc-001");
        }

    }
}
